repos:

  # Versioning: Commit messages & changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Lint / autoformat: Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.4.8"
    hooks:
      # Run the linter
      - id: ruff
        files: ^backend/(?:.*/)*.*$
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format
        files: ^backend/(?:.*/)*.*$

  # Spelling: Checks for common misspellings in text files.
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types: [text]
        args: [--toml, backend/pyproject.toml]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        entry: env PRETTIER_LEGACY_CLI=1 prettier
        args:
          [
            --ignore-unknown,
            --no-error-on-unmatched-pattern,
            "!chart/**",
            "!CHANGELOG.md",
            "!CONTRIBUTING.md"
          ]

  # Lint: Bash scripts
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.1
    hooks:
      - id: bashate
        files: ^(?!.*(?:^|/)contrib(?:/|$)).*$

  # Lint: Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^(?!.*(?:^|/)contrib(?:/|$)).*$
        args: ["-x", "--exclude=SC2317,SC2188,SC2143"]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args:
          [--fix, --disable, MD033, --ignore, CHANGELOG.md, --ignore, .github]

  # Trailing whitespace
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace

  # Black formatter
  -   repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
      -   id: black